// src/app/page.js
'use client'

import { useEffect } from 'react'
import Head from 'next/head'

export default function Home() {
  useEffect(() => {
    // Package button interactions
    const packageButtons = document.querySelectorAll('.package-button')
    packageButtons.forEach(button => {
      button.addEventListener('click', function() {
        const packageName = this.closest('.package-card').querySelector('.package-name').textContent
        alert(`Thank you for your interest in the ${packageName} package! Our strategic team will contact you within 24 hours to discuss your entrepreneurial vision and begin the NDA process.`)
      })
    })

    // Concept CTA interactions
    const conceptButtons = document.querySelectorAll('.concept-cta')
    conceptButtons.forEach(button => {
      button.addEventListener('click', function() {
        alert('Full concept details available exclusively through our strategic packages. Choose your package level to access our complete library of validated business opportunities.')
      })
    })

    // Subscription button
    const subscriptionButton = document.querySelector('[data-subscription]')
    if (subscriptionButton) {
      subscriptionButton.addEventListener('click', function() {
        alert('Thank you for your interest in our Strategy Insights Monthly subscription! You will be redirected to our secure payment portal.')
      })
    }

    // Smooth scrolling
    const anchors = document.querySelectorAll('a[href^="#"]')
    anchors.forEach(anchor => {
      anchor.addEventListener('click', function (e) {
        e.preventDefault()
        const target = document.querySelector(this.getAttribute('href'))
        if (target) {
          target.scrollIntoView({
            behavior: 'smooth',
            block: 'start'
          })
        }
      })
    })

    // Cleanup function
    return () => {
      packageButtons.forEach(button => {
        button.removeEventListener('click', () => {})
      })
      conceptButtons.forEach(button => {
        button.removeEventListener('click', () => {})
      })
      anchors.forEach(anchor => {
        anchor.removeEventListener('click', () => {})
      })
    }
  }, [])

  return (
    <>
      <Head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <meta name="theme-color" content="#1a1a1a" />
      </Head>

      {/* Header */}
      <header className="header">
        <nav className="nav container">
          <a href="#" className="logo">
            <i className="fas fa-cube"></i>
            Vorteca
          </a>
          <ul className="nav-links">
            <li><a href="#packages">Packages</a></li>
            <li><a href="#process">Process</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
          <a href="#packages" className="cta-button">Get Started</a>
        </nav>
      </header>

      {/* Hero Section */}
      <section className="hero">
        <div className="container">
          <div className="hero-content">
            <h1>Strategic Business Concepts</h1>
            <p className="hero-subtitle">We transform creative business vision into comprehensive, market-ready opportunity packages. Perfect for entrepreneurs with capital seeking validated, executable concepts.</p>
            
            <div className="hero-guarantee">
              <p>
                <i className="fas fa-shield-alt"></i>
                <strong>Full NDA Protection & Complete Confidentiality Guaranteed</strong>
              </p>
            </div>
            
            <div className="hero-buttons">
              <a href="#packages" className="primary-btn">Explore Concepts</a>
              <a href="#process" className="secondary-btn">How It Works</a>
            </div>
          </div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="stats">
        <div className="container">
          <div className="stats-grid">
            <div className="stat-item">
              <span className="stat-number">200+</span>
              <div className="stat-label">Business Concepts Crafted</div>
            </div>
            <div className="stat-item">
              <span className="stat-number">92%</span>
              <div className="stat-label">Client Launch Success Rate</div>
            </div>
            <div className="stat-item">
              <span className="stat-number">$4.1M</span>
              <div className="stat-label">Revenue Generated by Clients</div>
            </div>
            <div className="stat-item">
              <span className="stat-number">18</span>
              <div className="stat-label">Industries Mastered</div>
            </div>
          </div>
        </div>
      </section>

      {/* Featured Concepts Section */}
      <section className="featured-concepts">
        <div className="container">
          <div className="section-title">
            <h2>This Month&apos;s Featured Opportunities</h2>
            <p>New business concepts rotate monthly. Get exclusive access to our complete portfolio of validated opportunities with full strategic frameworks.</p>
          </div>
          
          <div style={{textAlign: 'center', marginBottom: '50px'}}>
            <div style={{display: 'inline-block', background: '#1a1a1a', color: 'white', padding: '12px 24px', borderRadius: '25px', fontWeight: '600', marginBottom: '10px'}}>September 2025 Spotlight</div>
            <p style={{color: '#666', fontStyle: 'italic'}}>Concepts refresh monthly - Premium concepts available exclusively to package holders</p>
          </div>
          
          <div className="concepts-grid">
            <div className="concept-card">
              <div style={{color: '#1a1a1a', fontSize: '0.9rem', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: '15px'}}>Fintech Opportunity</div>
              <h3 style={{fontSize: '1.4rem', fontWeight: '600', marginBottom: '15px', color: '#1a1a1a'}}>Automated Financial Service</h3>
              <p style={{color: '#666', lineHeight: '1.6', marginBottom: '20px'}}>Revolutionary approach to personal debt management using emerging AI technology. Targets $400B market with unique competitive positioning.</p>
              <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center'}}>
                <span style={{color: '#1a1a1a', fontWeight: '600', fontSize: '0.9rem'}}>Market Potential: $400B+</span>
                <button className="concept-cta">Access Full Concept</button>
              </div>
            </div>
            
            <div className="concept-card">
              <div style={{color: '#1a1a1a', fontSize: '0.9rem', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: '15px'}}>Life Enhancement</div>
              <h3 style={{fontSize: '1.4rem', fontWeight: '600', marginBottom: '15px', color: '#1a1a1a'}}>Personal Productivity Platform</h3>
              <p style={{color: '#666', lineHeight: '1.6', marginBottom: '20px'}}>AI-driven solution for life administration challenges. Addresses massive underserved market with proven demand validation.</p>
              <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center'}}>
                <span style={{color: '#1a1a1a', fontWeight: '600', fontSize: '0.9rem'}}>Market Potential: $85B+</span>
                <button className="concept-cta">Access Full Concept</button>
              </div>
            </div>
            
            <div className="concept-card">
              <div style={{color: '#1a1a1a', fontSize: '0.9rem', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: '15px'}}>Novel Innovation</div>
              <h3 style={{fontSize: '1.4rem', fontWeight: '600', marginBottom: '15px', color: '#1a1a1a'}}>Personalized Health Technology</h3>
              <p style={{color: '#666', lineHeight: '1.6', marginBottom: '20px'}}>Breakthrough application of genetic science for consumer products. First-mover advantage in rapidly expanding health-tech sector.</p>
              <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center'}}>
                <span style={{color: '#1a1a1a', fontWeight: '600', fontSize: '0.9rem'}}>Market Potential: $180B+</span>
                <button className="concept-cta">Access Full Concept</button>
              </div>
            </div>
          </div>
          
          <div style={{textAlign: 'center', marginTop: '50px'}}>
            <a href="#packages" className="primary-btn">View All Concept Categories</a>
          </div>
        </div>
      </section>

      {/* Concept Categories Section */}
      <section className="concept-categories">
        <div className="container">
          <div className="section-title">
            <h2>Strategic Concept Portfolio</h2>
            <p>Comprehensive library of business opportunities across high-growth sectors. Full concepts available exclusively through strategic packages.</p>
          </div>
          
          <div className="categories-grid">
            <div className="category-item">
              <div style={{fontSize: '3rem', marginBottom: '20px'}}>💳</div>
              <h3 style={{fontSize: '1.5rem', fontWeight: '600', marginBottom: '15px', color: '#1a1a1a'}}>Fintech Innovation</h3>
              <p style={{color: '#666', lineHeight: '1.6', marginBottom: '25px'}}>20 validated financial technology opportunities targeting underserved markets and emerging payment solutions.</p>
              <div style={{background: '#f8f9fa', padding: '20px', borderRadius: '8px', marginBottom: '20px'}}>
                <div style={{fontSize: '0.9rem', color: '#1a1a1a', fontWeight: '600', marginBottom: '8px'}}>Focus Areas Include:</div>
                <ul style={{listStyle: 'none', textAlign: 'left', color: '#666', fontSize: '0.9rem'}}>
                  <li style={{marginBottom: '5px'}}>• Automated financial management</li>
                  <li style={{marginBottom: '5px'}}>• Alternative investment platforms</li>
                  <li style={{marginBottom: '5px'}}>• Cross-border payment solutions</li>
                  <li style={{marginBottom: '5px'}}>• Behavioral finance applications</li>
                </ul>
              </div>
              <div style={{color: '#1a1a1a', fontWeight: '600'}}>Average Market Size: $200B+</div>
            </div>
            
            <div className="category-item">
              <div style={{fontSize: '3rem', marginBottom: '20px'}}>🏡</div>
              <h3 style={{fontSize: '1.5rem', fontWeight: '600', marginBottom: '15px', color: '#1a1a1a'}}>Life Enhancement</h3>
              <p style={{color: '#666', lineHeight: '1.6', marginBottom: '25px'}}>15 technology-enabled services that solve daily life challenges through automation and community building.</p>
              <div style={{background: '#f8f9fa', padding: '20px', borderRadius: '8px', marginBottom: '20px'}}>
                <div style={{fontSize: '0.9rem', color: '#1a1a1a', fontWeight: '600', marginBottom: '8px'}}>Focus Areas Include:</div>
                <ul style={{listStyle: 'none', textAlign: 'left', color: '#666', fontSize: '0.9rem'}}>
                  <li style={{marginBottom: '5px'}}>• Personal productivity automation</li>
                  <li style={{marginBottom: '5px'}}>• Health optimization services</li>
                  <li style={{marginBottom: '5px'}}>• Community connection platforms</li>
                  <li style={{marginBottom: '5px'}}>• Sustainable living solutions</li>
                </ul>
              </div>
              <div style={{color: '#1a1a1a', fontWeight: '600'}}>Average Market Size: $120B+</div>
            </div>
            
            <div className="category-item">
              <div style={{fontSize: '3rem', marginBottom: '20px'}}>🚀</div>
              <h3 style={{fontSize: '1.5rem', fontWeight: '600', marginBottom: '15px', color: '#1a1a1a'}}>Novel Technology</h3>
              <p style={{color: '#666', lineHeight: '1.6', marginBottom: '25px'}}>15 breakthrough concepts combining emerging technology with untapped market opportunities for first-mover advantage.</p>
              <div style={{background: '#f8f9fa', padding: '20px', borderRadius: '8px', marginBottom: '20px'}}>
                <div style={{fontSize: '0.9rem', color: '#1a1a1a', fontWeight: '600', marginBottom: '8px'}}>Focus Areas Include:</div>
                <ul style={{listStyle: 'none', textAlign: 'left', color: '#666', fontSize: '0.9rem'}}>
                  <li style={{marginBottom: '5px'}}>• Personalized biotechnology</li>
                  <li style={{marginBottom: '5px'}}>• Immersive experience platforms</li>
                  <li style={{marginBottom: '5px'}}>• Advanced communication systems</li>
                  <li style={{marginBottom: '5px'}}>• Environmental innovation</li>
                </ul>
              </div>
              <div style={{color: '#1a1a1a', fontWeight: '600'}}>Average Market Size: $150B+</div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="features" id="about">
        <div className="container">
          <div className="section-title">
            <h2>Why Choose Vorteca?</h2>
            <p>We don&apos;t just generate business ideas – we architect complete strategic frameworks that position you for immediate competitive advantage.</p>
          </div>
          <div className="features-grid">
            <div className="feature-card">
              <div className="feature-icon">
                <i className="fas fa-brain"></i>
              </div>
              <h3>Strategic Intelligence</h3>
              <p>Every concept undergoes rigorous strategic analysis, market validation, and competitive positioning before development.</p>
            </div>
            <div className="feature-card">
              <div className="feature-icon">
                <i className="fas fa-rocket"></i>
              </div>
              <h3>Launch-Ready Frameworks</h3>
              <p>Complete execution blueprints with operational workflows, financial modeling, and strategic implementation timelines.</p>
            </div>
            <div className="feature-card">
              <div className="feature-icon">
                <i className="fas fa-dollar-sign"></i>
              </div>
              <h3>Proven ROI Models</h3>
              <p>All concepts include detailed financial projections showing clear paths to profitability and sustainable growth.</p>
            </div>
            <div className="feature-card">
              <div className="feature-icon">
                <i className="fas fa-users"></i>
              </div>
              <h3>Expert Partnership</h3>
              <p>Access to our network of industry strategists and market experts throughout your implementation journey.</p>
            </div>
            <div className="feature-card">
              <div className="feature-icon">
                <i className="fas fa-shield-alt"></i>
              </div>
              <h3>Complete Confidentiality</h3>
              <p>Full NDA protection and privacy guarantee. Your business concepts remain completely confidential with zero data sharing.</p>
            </div>
          </div>
        </div>
      </section>

      {/* Packages Section */}
      <section className="packages" id="packages">
        <div className="container">
          <div className="section-title">
            <h2>Strategic Concept Access</h2>
            <p>Choose your engagement level - from monthly insights to complete strategic business blueprints with full NDA protection.</p>
          </div>
          
          {/* Subscription Option */}
          <div style={{background: 'linear-gradient(135deg, #1a1a1a 0%, #2d2d2d 100%)', color: 'white', padding: '50px 0', borderRadius: '20px', marginBottom: '50px'}}>
            <div style={{textAlign: 'center', marginBottom: '40px'}}>
              <h3 style={{fontSize: '2rem', marginBottom: '15px'}}>New: Monthly Strategy Subscription</h3>
              <p style={{fontSize: '1.1rem', opacity: '0.9'}}>Access market intelligence, trend reports, and concept seeds without full strategic development</p>
            </div>
            
            <div style={{maxWidth: '800px', margin: '0 auto', background: 'rgba(255, 255, 255, 0.1)', padding: '40px', borderRadius: '15px', backdropFilter: 'blur(10px)'}}>
              <div style={{display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '20px'}}>
                <div>
                  <h4 style={{fontSize: '1.3rem', marginBottom: '10px'}}>Strategy Insights Monthly</h4>
                  <p style={{opacity: '0.9', marginBottom: '15px'}}>Perfect for aspiring entrepreneurs who want market intelligence and business idea inspiration</p>
                  <ul style={{listStyle: 'none', fontSize: '0.9rem'}}>
                    <li style={{marginBottom: '5px'}}>✓ Monthly industry trend reports</li>
                    <li style={{marginBottom: '5px'}}>✓ Business concept &quot;seeds&quot; and market opportunities</li>
                    <li style={{marginBottom: '5px'}}>✓ Strategic framework templates</li>
                    <li style={{marginBottom: '5px'}}>✓ Access to monthly strategy webinars</li>
                  </ul>
                </div>
                <div style={{textAlign: 'center'}}>
                  <div style={{fontSize: '2.5rem', fontWeight: '800', marginBottom: '5px'}}>$47<span style={{fontSize: '1rem', opacity: '0.8'}}>/month</span></div>
                  <button data-subscription style={{background: 'white', color: '#1a1a1a', padding: '12px 24px', border: 'none', borderRadius: '8px', fontWeight: '600', cursor: 'pointer'}}>Start Subscription</button>
                </div>
              </div>
            </div>
          </div>

          <div className="packages-grid">
            <div className="package-card">
              <div className="package-header">
                <div className="package-name">Foundation</div>
                <div className="package-price">$397</div>
                <div className="package-description">Essential framework + concept access</div>
              </div>
              <div className="package-content">
                <div style={{background: 'rgba(26, 26, 26, 0.05)', padding: '20px', borderRadius: '8px', marginBottom: '25px'}}>
                  <h4 style={{color: '#1a1a1a', marginBottom: '10px', fontSize: '1rem'}}>Complete Strategic Framework Access:</h4>
                  <p style={{color: '#666', fontSize: '0.9rem', lineHeight: '1.5'}}>Curated library of validated business opportunities across multiple high-growth sectors. Full concept details revealed upon package selection and NDA execution.</p>
                </div>
                <ul className="package-features">
                  <li><i className="fas fa-check"></i> Access to complete concept library</li>
                  <li><i className="fas fa-check"></i> Strategic concept overview</li>
                  <li><i className="fas fa-check"></i> Market opportunity analysis</li>
                  <li><i className="fas fa-check"></i> Revenue framework design</li>
                  <li><i className="fas fa-check"></i> 12-step execution roadmap</li>
                  <li><i className="fas fa-check"></i> Competitive intelligence brief</li>
                  <li><i className="fas fa-check"></i> Strategic consultation call</li>
                  <li><i className="fas fa-check"></i> Full NDA protection</li>
                </ul>
                <button className="package-button">Choose Foundation</button>
              </div>
            </div>
            
            <div className="package-card featured">
              <div className="popular-badge">Most Popular</div>
              <div className="package-header">
                <div className="package-name">Architect</div>
                <div className="package-price">$1,197</div>
                <div className="package-description">Comprehensive strategic business architecture</div>
              </div>
              <div className="package-content">
                <div style={{background: 'rgba(26, 26, 26, 0.05)', padding: '20px', borderRadius: '8px', marginBottom: '25px'}}>
                  <h4 style={{color: '#1a1a1a', marginBottom: '10px', fontSize: '1rem'}}>Advanced Strategic Architecture:</h4>
                  <p style={{color: '#666', fontSize: '0.9rem', lineHeight: '1.5'}}>Comprehensive business development with deep strategic frameworks and operational specifications. Complete architecture scope revealed upon selection.</p>
                </div>
                <ul className="package-features">
                  <li><i className="fas fa-check"></i> Everything in Foundation, plus:</li>
                  <li><i className="fas fa-check"></i> 3-year financial architecture</li>
                  <li><i className="fas fa-check"></i> Strategic marketing framework</li>
                  <li><i className="fas fa-check"></i> Operational system design</li>
                  <li><i className="fas fa-check"></i> Risk intelligence & mitigation</li>
                  <li><i className="fas fa-check"></i> Strategic partner identification</li>
                  <li><i className="fas fa-check"></i> Brand positioning strategy</li>
                  <li><i className="fas fa-check"></i> Priority strategic support</li>
                </ul>
                <button className="package-button">Choose Architect</button>
              </div>
            </div>
            
            <div className="package-card">
              <div className="package-header">
                <div className="package-name">Enterprise</div>
                <div className="package-price">$2,997</div>
                <div className="package-description">Complete market-domination blueprint</div>
              </div>
              <div className="package-content">
                <div style={{background: 'rgba(26, 26, 26, 0.05)', padding: '20px', borderRadius: '8px', marginBottom: '25px'}}>
                  <h4 style={{color: '#1a1a1a', marginBottom: '10px', fontSize: '1rem'}}>Executive Strategic Blueprint:</h4>
                  <p style={{color: '#666', fontSize: '0.9rem', lineHeight: '1.5'}}>Complete market-domination package with legal compliance, operational specifications, and executive-level strategic frameworks. Full scope revealed upon engagement.</p>
                </div>
                <ul className="package-features">
                  <li><i className="fas fa-check"></i> Everything in Architect, plus:</li>
                  <li><i className="fas fa-check"></i> Legal structure optimization</li>
                  <li><i className="fas fa-check"></i> Regulatory compliance roadmap</li>
                  <li><i className="fas fa-check"></i> Technology architecture specs</li>
                  <li><i className="fas fa-check"></i> Team scaling blueprint</li>
                  <li><i className="fas fa-check"></i> 12-month strategic calendar</li>
                  <li><i className="fas fa-check"></i> Performance analytics framework</li>
                  <li><i className="fas fa-check"></i> 90-day launch sprint plan</li>
                  <li><i className="fas fa-check"></i> Executive strategy sessions</li>
                </ul>
                <button className="package-button">Choose Enterprise</button>
              </div>
            </div>
          </div>
          
          <div style={{textAlign: 'center', marginTop: '50px', background: 'rgba(26, 26, 26, 0.05)', padding: '30px', borderRadius: '12px'}}>
            <h3 style={{color: '#1a1a1a', marginBottom: '15px'}}>Strategic Portfolio Overview:</h3>
            <div style={{display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: '20px', marginTop: '20px'}}>
              <div>
                <strong style={{color: '#1a1a1a'}}>Fintech Solutions (20 concepts)</strong>
                <p style={{color: '#666', fontSize: '0.9rem'}}>Advanced financial technology opportunities targeting underserved markets and emerging trends</p>
              </div>
              <div>
                <strong style={{color: '#1a1a1a'}}>Life Enhancement (15 concepts)</strong>
                <p style={{color: '#666', fontSize: '0.9rem'}}>Technology-enabled services that solve daily challenges through innovation and automation</p>
              </div>
              <div>
                <strong style={{color: '#1a1a1a'}}>Novel Technology (15 concepts)</strong>
                <p style={{color: '#666', fontSize: '0.9rem'}}>Breakthrough applications combining emerging technology with untapped market opportunities</p>
              </div>
            </div>
            <p style={{color: '#666', fontSize: '0.9rem', marginTop: '20px', fontStyle: 'italic'}}>Full concept details and strategic frameworks available exclusively through package selection</p>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="footer">
        <div className="container">
          <div className="footer-content">
            <div className="footer-section">
              <h3>Vorteca</h3>
              <p>Transforming creative business vision into strategic, market-ready opportunities for ambitious entrepreneurs worldwide. Full confidentiality and IP protection guaranteed.</p>
            </div>
            
            <div className="footer-section">
              <h3>Strategic Services</h3>
              <ul>
                <li><a href="#packages">Foundation Package</a></li>
                <li><a href="#packages">Architect Package</a></li>
                <li><a href="#packages">Enterprise Package</a></li>
                <li><a href="#">Custom Concept Development</a></li>
              </ul>
            </div>
            
            <div className="footer-section">
              <h3>Resources</h3>
              <ul>
                <li><a href="#">Strategic Case Studies</a></li>
                <li><a href="#">Business Intelligence Blog</a></li>
                <li><a href="#">Market Opportunity Reports</a></li>
                <li><a href="#">Execution Frameworks</a></li>
              </ul>
            </div>
            
            <div className="footer-section">
              <h3>Connect</h3>
              <ul>
                <li>Email: hello@myvorteca.com</li>
                <li>Strategic Hotline: (555) 123-4567</li>
                <li>Address: 789 Strategy Lane<br />Austin, TX 78701</li>
              </ul>
            </div>
          </div>
          
          <div className="footer-bottom">
            <p>&copy; 2025 Vorteca. All rights reserved. | Privacy Policy | Terms of Service | NDA Policy</p>
          </div>
        </div>
      </footer>
    </>
  )
}